"""add request_payload to address_validation_batches

Revision ID: b894d9fe3c38
Revises: 3da570216414
Create Date: 2026-01-10 00:24:03.520582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b894d9fe3c38'
down_revision: Union[str, Sequence[str], None] = '3da570216414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_validation_batches', sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address_validation_batches', 'request_payload')
    # ### end Alembic commands ###
